_base_: ../default.yaml

data:
  fd_subset: FD001

features:
  # Constant: s_1, s_10, s_18, s_19
  # Failed correlation filter (|r| < 0.1): s_5, s_16
  sensor_cols_to_drop:
    - s_1
    - s_5
    - s_10
    - s_16
    - s_18
    - s_19
  n_modes: 1
